package ihh.spellbound;

import com.google.common.collect.Lists;
import net.minecraft.potion.Effect;
import net.minecraft.potion.EffectInstance;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.config.ModConfig;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.ArrayList;
import java.util.List;

public final class Config {
    static ForgeConfigSpec config;
    private static ForgeConfigSpec.Builder b;
    public static ForgeConfigSpec.IntValue ADVANCE_TIME_USE_DURATION;
    public static ForgeConfigSpec.IntValue ARCHMAGIC_USE_DURATION;
    public static ForgeConfigSpec.IntValue AREA_LIGHTNING_USE_DURATION;
    public static ForgeConfigSpec.IntValue BEDROCK_WALL_USE_DURATION;
    public static ForgeConfigSpec.IntValue BLINK_USE_DURATION;
    public static ForgeConfigSpec.IntValue BREACH_USE_DURATION;
    public static ForgeConfigSpec.IntValue CHANGE_WEATHER_USE_DURATION;
    public static ForgeConfigSpec.IntValue CHAOS_USE_DURATION;
    public static ForgeConfigSpec.IntValue COLD_BLAST_USE_DURATION;
    public static ForgeConfigSpec.IntValue COLD_SHIELD_USE_DURATION;
    public static ForgeConfigSpec.IntValue COLOR_SPRAY_USE_DURATION;
    public static ForgeConfigSpec.IntValue COOKIE_CHEST_USE_DURATION;
    public static ForgeConfigSpec.IntValue DIMENSION_DOOR_USE_DURATION;
    public static ForgeConfigSpec.IntValue DISINTEGRATE_USE_DURATION;
    public static ForgeConfigSpec.IntValue ELEMENTAL_FURY_USE_DURATION;
    public static ForgeConfigSpec.IntValue FIREBALL_USE_DURATION;
    public static ForgeConfigSpec.IntValue FIRE_SHIELD_USE_DURATION;
    public static ForgeConfigSpec.IntValue FISH_FORM_USE_DURATION;
    public static ForgeConfigSpec.IntValue FLAMING_HANDS_USE_DURATION;
    public static ForgeConfigSpec.IntValue FLIGHT_USE_DURATION;
    public static ForgeConfigSpec.IntValue GREATER_FIREBALL_USE_DURATION;
    public static ForgeConfigSpec.IntValue HASTE_USE_DURATION;
    public static ForgeConfigSpec.IntValue ICICLE_USE_DURATION;
    public static ForgeConfigSpec.IntValue ICY_GRIP_USE_DURATION;
    public static ForgeConfigSpec.IntValue INSTANT_LEVITATION_USE_DURATION;
    public static ForgeConfigSpec.IntValue LIGHTNING_BOLT_USE_DURATION;
    public static ForgeConfigSpec.IntValue LIGHTNING_SHIELD_USE_DURATION;
    public static ForgeConfigSpec.IntValue MISCAST_MAGIC_USE_DURATION;
    public static ForgeConfigSpec.IntValue OBSIDIAN_WALL_USE_DURATION;
    public static ForgeConfigSpec.IntValue PANIC_ROOM_USE_DURATION;
    public static ForgeConfigSpec.IntValue PUSH_USE_DURATION;
    public static ForgeConfigSpec.IntValue SPELL_SHIELD_USE_DURATION;
    public static ForgeConfigSpec.IntValue STONE_WALL_USE_DURATION;
    public static ForgeConfigSpec.IntValue SUMMON_SKELETON_USE_DURATION;
    public static ForgeConfigSpec.IntValue SUMMON_WITHER_SKELETON_USE_DURATION;
    public static ForgeConfigSpec.IntValue SUMMON_WOLF_USE_DURATION;
    public static ForgeConfigSpec.IntValue SURGE_SHIELD_USE_DURATION;
    public static ForgeConfigSpec.IntValue TASER_USE_DURATION;
    public static ForgeConfigSpec.IntValue TORCHLIGHT_USE_DURATION;
    public static ForgeConfigSpec.IntValue WAIL_OF_THE_SHE_WOLF_USE_DURATION;
    public static ForgeConfigSpec.IntValue ADVANCE_TIME_MIN;
    public static ForgeConfigSpec.IntValue ADVANCE_TIME_MAX;
    public static ForgeConfigSpec.IntValue ADVANCE_TIME_RANGE;
    public static ForgeConfigSpec.IntValue ARCHMAGIC_DURATION;
    public static ForgeConfigSpec.IntValue AREA_LIGHTNING_DAMAGE;
    public static ForgeConfigSpec.IntValue AREA_LIGHTNING_DURATION;
    public static ForgeConfigSpec.IntValue AREA_LIGHTNING_RANGE;
    public static ForgeConfigSpec.IntValue BEDROCK_WALL_HORIZONTAL;
    public static ForgeConfigSpec.IntValue BEDROCK_WALL_VERTICAL;
    public static ForgeConfigSpec.IntValue BLINK_DURATION;
    public static ForgeConfigSpec.IntValue BREACH_RANGE;
    public static ForgeConfigSpec.IntValue CHANGE_WEATHER_MIN;
    public static ForgeConfigSpec.IntValue CHANGE_WEATHER_MAX;
    public static ForgeConfigSpec.IntValue CHAOS_DURATION;
    public static ForgeConfigSpec.IntValue COLD_BLAST_RANGE;
    public static ForgeConfigSpec.IntValue COLD_BLAST_DURATION;
    public static ForgeConfigSpec.IntValue COLD_BLAST_DAMAGE;
    public static ForgeConfigSpec.IntValue COLD_SHIELD_DURATION;
    public static ForgeConfigSpec.IntValue COLOR_SPRAY_RANGE;
    public static ForgeConfigSpec.IntValue COLOR_SPRAY_DURATION;
    public static ForgeConfigSpec.IntValue DIMENSION_DOOR_MIN;
    public static ForgeConfigSpec.IntValue DIMENSION_DOOR_MAX;
    public static ForgeConfigSpec.IntValue DISINTEGRATE_DURATION;
    public static ForgeConfigSpec.IntValue DISINTEGRATE_DAMAGE;
    public static ForgeConfigSpec.IntValue ELEMENTAL_FURY_HORIZONTAL;
    public static ForgeConfigSpec.IntValue FIREBALL_DAMAGE;
    public static ForgeConfigSpec.IntValue FIRE_SHIELD_DURATION;
    public static ForgeConfigSpec.IntValue FISH_FORM_DURATION;
    public static ForgeConfigSpec.IntValue FLAMING_HANDS_DAMAGE;
    public static ForgeConfigSpec.IntValue FLAMING_HANDS_RANGE;
    public static ForgeConfigSpec.IntValue FLIGHT_DURATION;
    public static ForgeConfigSpec.IntValue GREATER_FIREBALL_DAMAGE;
    public static ForgeConfigSpec.IntValue HASTE_DURATION;
    public static ForgeConfigSpec.IntValue ICICLE_RANGE;
    public static ForgeConfigSpec.IntValue ICICLE_DURATION;
    public static ForgeConfigSpec.IntValue ICICLE_DAMAGE;
    public static ForgeConfigSpec.IntValue ICY_GRIP_RANGE;
    public static ForgeConfigSpec.IntValue ICY_GRIP_DURATION;
    public static ForgeConfigSpec.IntValue ICY_GRIP_DAMAGE;
    public static ForgeConfigSpec.IntValue INSTANT_LEVITATION_RANGE;
    public static ForgeConfigSpec.IntValue LIGHTNING_BOLT_DAMAGE;
    public static ForgeConfigSpec.IntValue LIGHTNING_BOLT_DURATION;
    public static ForgeConfigSpec.IntValue LIGHTNING_SHIELD_DURATION;
    public static ForgeConfigSpec.IntValue MISCAST_MAGIC_DURATION;
    public static ForgeConfigSpec.IntValue OBSIDIAN_WALL_HORIZONTAL;
    public static ForgeConfigSpec.IntValue OBSIDIAN_WALL_VERTICAL;
    public static ForgeConfigSpec.IntValue PUSH_RANGE;
    public static ForgeConfigSpec.IntValue PUSH_DAMAGE;
    public static ForgeConfigSpec.IntValue PUSH_STRENGTH;
    public static ForgeConfigSpec.IntValue SPELL_SHIELD_DURATION;
    public static ForgeConfigSpec.IntValue STONE_WALL_HORIZONTAL;
    public static ForgeConfigSpec.IntValue STONE_WALL_VERTICAL;
    public static ForgeConfigSpec.IntValue SURGE_SHIELD_DURATION;
    public static ForgeConfigSpec.IntValue TASER_DURATION;
    public static ForgeConfigSpec.IntValue TASER_DAMAGE;
    public static ForgeConfigSpec.IntValue WAIL_OF_THE_SHE_WOLF_RANGE;
    public static ForgeConfigSpec.IntValue WAIL_OF_THE_SHE_WOLF_DAMAGE;
    public static ForgeConfigSpec.IntValue SURGE_CHANCE;
    public static ForgeConfigSpec.IntValue SURGE_CHAOS_CHANCE;
    public static ForgeConfigSpec.IntValue SURGE_FIRE;
    public static ForgeConfigSpec.BooleanValue SURGE_POTION;
    private static final ForgeConfigSpec.ConfigValue<List<? extends String>> SURGE_POTIONS;
    private static final ArrayList<String> SURGE_DEFAULT_POTIONS = Lists.newArrayList("minecraft:weakness;200;0;true;true", "minecraft:poison;200;0;true;true");
    public static ArrayList<EffectInstance> SURGE_EFFECTS = new ArrayList<>();

    static {
        Config.b = new ForgeConfigSpec.Builder();
        b.comment("How long the spells need to be charged, in ticks.");
        push("spell_time");
        ADVANCE_TIME_USE_DURATION = defineTime("advance_time", 60);
        ARCHMAGIC_USE_DURATION = defineTime("archmagic", 100);
        AREA_LIGHTNING_USE_DURATION = defineTime("area_lightning", 60);
        BEDROCK_WALL_USE_DURATION = defineTime("bedrock_wall", 80);
        BLINK_USE_DURATION = defineTime("blink", 40);
        BREACH_USE_DURATION = defineTime("breach", 40);
        CHANGE_WEATHER_USE_DURATION = defineTime("change_weather", 60);
        CHAOS_USE_DURATION = defineTime("chaos", 60);
        COLD_BLAST_USE_DURATION = defineTime("cold_blast", 60);
        COLD_SHIELD_USE_DURATION = defineTime("cold_shield", 20);
        COLOR_SPRAY_USE_DURATION = defineTime("color_spray", 40);
        COOKIE_CHEST_USE_DURATION = defineTime("cookie_chest", 80);
        DIMENSION_DOOR_USE_DURATION = defineTime("dimension_door", 80);
        DISINTEGRATE_USE_DURATION = defineTime("disintegrate", 100);
        ELEMENTAL_FURY_USE_DURATION = defineTime("elemental_fury", 100);
        FIREBALL_USE_DURATION = defineTime("fireball", 40);
        FIRE_SHIELD_USE_DURATION = defineTime("fire_shield", 20);
        FISH_FORM_USE_DURATION = defineTime("fish_form", 40);
        FLAMING_HANDS_USE_DURATION = defineTime("flaming_hands", 20);
        FLIGHT_USE_DURATION = defineTime("flight", 80);
        GREATER_FIREBALL_USE_DURATION = defineTime("greater_fireball", 60);
        HASTE_USE_DURATION = defineTime("haste", 40);
        ICICLE_USE_DURATION = defineTime("icicle", 40);
        ICY_GRIP_USE_DURATION = defineTime("icy_grip", 20);
        INSTANT_LEVITATION_USE_DURATION = defineTime("instant_levitation", 0);
        LIGHTNING_BOLT_USE_DURATION = defineTime("lightning_bolt", 40);
        LIGHTNING_SHIELD_USE_DURATION = defineTime("lightning_shield", 20);
        MISCAST_MAGIC_USE_DURATION = defineTime("miscast_magic", 60);
        OBSIDIAN_WALL_USE_DURATION = defineTime("obsidian_wall", 80);
        PANIC_ROOM_USE_DURATION = defineTime("panic_room", 100);
        PUSH_USE_DURATION = defineTime("push", 40);
        SPELL_SHIELD_USE_DURATION = defineTime("spell_shield", 100);
        STONE_WALL_USE_DURATION = defineTime("stone_wall", 80);
        SUMMON_SKELETON_USE_DURATION = defineTime("summon_skeleton", 40);
        SUMMON_WITHER_SKELETON_USE_DURATION = defineTime("summon_wither_skeleton", 60);
        SUMMON_WOLF_USE_DURATION = defineTime("summon_wolf", 20);
        SURGE_SHIELD_USE_DURATION = defineTime("surge_shield", 20);
        TASER_USE_DURATION = defineTime("taser", 20);
        TORCHLIGHT_USE_DURATION = defineTime("torchlight", 0);
        WAIL_OF_THE_SHE_WOLF_USE_DURATION = defineTime("wail_of_the_she_wolf", 100);
        pop();
        b.comment("Modify the effects of spells.");
        push("spell");
        push("advance_time");
        ADVANCE_TIME_MIN = defineInt("The minimum. Must be lower than max.", "min", 1, 1, 24000);
        ADVANCE_TIME_MAX = defineInt("The maximum. Must be higher than min.", "max", 24000, 1, 24000);
        ADVANCE_TIME_RANGE = defineInt("The range.", "range", 32, 0, 32);
        pop();
        push("archmagic");
        ARCHMAGIC_DURATION = defineInt("The effect duration, in ticks.", "duration", 400, 0, 1000000);
        pop();
        push("area_lightning");
        AREA_LIGHTNING_DAMAGE = defineInt("The damage.", "damage", 10, 0, Integer.MAX_VALUE);
        AREA_LIGHTNING_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        AREA_LIGHTNING_RANGE = defineInt("The range.", "range", 16, 0, 32);
        pop();
        push("bedrock_wall");
        BEDROCK_WALL_HORIZONTAL = defineInt("The horizontal range.", "horizontal", 2, 0, 32);
        BEDROCK_WALL_VERTICAL = defineInt("The vertical range.", "vertical", 3, 0, 32);
        pop();
        push("blink");
        BLINK_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("breach");
        BREACH_RANGE = defineInt("The range.", "range", 1, 0, 32);
        pop();
        push("change_weather");
        CHANGE_WEATHER_MIN = defineInt("The minimum. Must be lower than max.", "min", 1, 1, 24000);
        CHANGE_WEATHER_MAX = defineInt("The maximum. Must be higher than min.", "max", 24000, 1, 24000);
        pop();
        push("chaos");
        CHAOS_DURATION = defineInt("The effect duration, in ticks.", "duration", 200, 0, 1000000);
        pop();
        push("cold_blast");
        COLD_BLAST_DAMAGE = defineInt("The damage.", "damage", 10, 0, Integer.MAX_VALUE);
        COLD_BLAST_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        COLD_BLAST_RANGE = defineInt("The range.", "range", 10, 0, 32);
        pop();
        push("cold_shield");
        COLD_SHIELD_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("color_spray");
        COLOR_SPRAY_DURATION = defineInt("The effect duration, in ticks.", "duration", 200, 0, 1000000);
        COLOR_SPRAY_RANGE = defineInt("The range.", "range", 16, 0, 32);
        pop();
        push("dimension_door");
        DIMENSION_DOOR_MIN = defineInt("The minimum. Must be lower than max.", "min", 192, 0, 1024);
        DIMENSION_DOOR_MAX = defineInt("The maximum. Must be higher than min.", "max", 256, 0, 1024);
        pop();
        push("disintegrate");
        DISINTEGRATE_DAMAGE = defineInt("The damage.", "damage", 100, 0, Integer.MAX_VALUE);
        DISINTEGRATE_DURATION = defineInt("The fire duration, in ticks.", "duration", 10, 0, 1000000);
        pop();
        push("elemental_fury");
        ELEMENTAL_FURY_HORIZONTAL = defineInt("The range.", "range", 16, 0, 32);
        pop();
        push("fireball");
        FIREBALL_DAMAGE = defineInt("The damage.", "damage", 8, 0, Integer.MAX_VALUE);
        pop();
        push("fire_shield");
        FIRE_SHIELD_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("fish_form");
        FISH_FORM_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("flaming_hands");
        FLAMING_HANDS_DAMAGE = defineInt("The damage.", "damage", 4, 0, Integer.MAX_VALUE);
        FLAMING_HANDS_RANGE = defineInt("The range.", "range", 4, 0, 32);
        pop();
        push("flight");
        FLIGHT_DURATION = defineInt("The effect duration, in ticks.", "duration", 400, 0, 1000000);
        pop();
        push("greater_fireball");
        GREATER_FIREBALL_DAMAGE = defineInt("The damage.", "damage", 10, 0, Integer.MAX_VALUE);
        pop();
        push("haste");
        HASTE_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("icicle");
        ICICLE_DAMAGE = defineInt("The damage.", "damage", 8, 0, Integer.MAX_VALUE);
        ICICLE_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        ICICLE_RANGE = defineInt("The range.", "range", 6, 0, 32);
        pop();
        push("icy_grip");
        ICY_GRIP_DAMAGE = defineInt("The damage.", "damage", 4, 0, Integer.MAX_VALUE);
        ICY_GRIP_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        ICY_GRIP_RANGE = defineInt("The range.", "range", 2, 0, 32);
        pop();
        push("instant_levitation");
        INSTANT_LEVITATION_RANGE = defineInt("The range.", "range", 4, 0, 32);
        pop();
        push("lightning_bolt");
        LIGHTNING_BOLT_DAMAGE = defineInt("The damage.", "damage", 8, 0, Integer.MAX_VALUE);
        LIGHTNING_BOLT_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("lightning_shield");
        LIGHTNING_SHIELD_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("miscast_magic");
        MISCAST_MAGIC_DURATION = defineInt("The effect duration, in ticks.", "duration", 200, 0, 1000000);
        pop();
        push("obsidian_wall");
        OBSIDIAN_WALL_HORIZONTAL = defineInt("The horizontal range.", "horizontal", 2, 0, 32);
        OBSIDIAN_WALL_VERTICAL = defineInt("The vertical range.", "vertical", 3, 0, 32);
        pop();
        push("push");
        PUSH_DAMAGE = defineInt("The damage.", "damage", 1, 0, Integer.MAX_VALUE);
        PUSH_RANGE = defineInt("The range.", "range", 16, 0, 32);
        PUSH_STRENGTH = defineInt("The knockback strength.", "strength", 8, 0, Integer.MAX_VALUE);
        pop();
        push("spell_shield");
        SPELL_SHIELD_DURATION = defineInt("The effect duration, in ticks.", "duration", 400, 0, 1000000);
        pop();
        push("stone_wall");
        STONE_WALL_HORIZONTAL = defineInt("The horizontal range.", "horizontal", 2, 0, 32);
        STONE_WALL_VERTICAL = defineInt("The vertical range.", "vertical", 3, 0, 32);
        pop();
        push("surge_shield");
        SURGE_SHIELD_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("taser");
        TASER_DAMAGE = defineInt("The damage.", "damage", 4, 0, Integer.MAX_VALUE);
        TASER_DURATION = defineInt("The effect duration, in ticks.", "duration", 1200, 0, 1000000);
        pop();
        push("wail_of_the_she_wolf");
        WAIL_OF_THE_SHE_WOLF_DAMAGE = defineInt("The damage.", "damage", 20, 0, Integer.MAX_VALUE);
        WAIL_OF_THE_SHE_WOLF_RANGE = defineInt("The range.", "range", 16, 0, 32);
        pop();
        pop();
        push("surge");
        SURGE_CHANCE = b.comment("The chance (1 in X) for surges to occur. Set to 0 to disable surges entirely.").defineInRange("chance", 200, 0, 1000000);
        SURGE_CHAOS_CHANCE = b.comment("The chance (1 in X) for surges to occur when the Chaos effect is active. Set to 0 to disable surges when the Chaos effect is active.").defineInRange("chaos_chance", 2, 0, 1000000);
        SURGE_FIRE = b.comment("How long the fire surge sets you on fire. Set to 0 to disable.").defineInRange("fire", 10, 0, 1000);
        SURGE_POTION = b.comment("Whether the potion surge is enabled or not.").define("potion", true);
        SURGE_POTIONS = b.comment("List of potion surges. Format is \"registryName duration amplifier showParticles\". Think of it as if the entries were in the command \"/effect give @s ...\"").defineList("potions", SURGE_DEFAULT_POTIONS, e -> (e instanceof String) && ((String) e).split(" ").length >= 2 && ((String) e).split(" ").length <= 4);
        pop();
        config = b.build();
    }

    private static void push(String s) {
        b.push(s);
    }

    private static void pop() {
        b.pop();
    }

    private static ForgeConfigSpec.IntValue defineInt(String c, String s, int v, int min, int max) {
        return b.comment(c).defineInRange(s, v, min, max);
    }

    private static ForgeConfigSpec.IntValue defineTime(String s, int i) {
        return b.defineInRange(s, i, 0, 72000);
    }

    @SubscribeEvent
    public static void reload(ModConfig.ModConfigEvent event) {
        if (event.getConfig().getType() == ModConfig.Type.SERVER) {
            SURGE_EFFECTS.clear();
            SURGE_POTIONS.get().stream().map(s -> s.split(" ")).filter(s -> s.length >= 2 && s.length <= 4).forEach(s -> {
                try {
                    Effect e = ForgeRegistries.POTIONS.getValue(new ResourceLocation(s[0]));
                    if (e == null) return;
                    int duration = Integer.parseInt(s[1]);
                    int amplifier = Integer.parseInt(s[2]);
                    boolean particles = Boolean.parseBoolean(s[3]);
                    SURGE_EFFECTS.add(new EffectInstance(e, duration <= 1 ? 1 : Math.min(duration, 1000000), amplifier <= 0 ? 0 : Math.min(amplifier, 127), false, particles));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
    }
}
