modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="spellbound"
version="${file.jarVersion}"
displayName="Spellbound: Legacy Version"
displayURL="http://www.curseforge.com/minecraft/mc-mods/spellbound-legacy-version"
authors="IchHabeHunger54"
logoFile="spellbound.png"
description='''
A remake of WildBamaBoy's 1.6 Spellbound Mod for Minecraft 1.15+, adding over 40 funny spells to the game!
'''
[[dependencies.spellbound]]
modId="forge"
versionRange="[36,)"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.spellbound]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
