package ihh.spellbound.init;

import ihh.spellbound.Config;
import ihh.spellbound.Spellbound;
import ihh.spellbound.item.AdvanceTime;
import ihh.spellbound.item.AreaLightning;
import ihh.spellbound.item.BedrockWall;
import ihh.spellbound.item.BeneficialPotionSpell;
import ihh.spellbound.item.Breach;
import ihh.spellbound.item.ChangeWeather;
import ihh.spellbound.item.ColdBlast;
import ihh.spellbound.item.ColorSpray;
import ihh.spellbound.item.CookieChest;
import ihh.spellbound.item.DimensionDoor;
import ihh.spellbound.item.Disintegrate;
import ihh.spellbound.item.ElementalFury;
import ihh.spellbound.item.Fireball;
import ihh.spellbound.item.FlamingHands;
import ihh.spellbound.item.GreaterFireball;
import ihh.spellbound.item.HarmfulPotionSpell;
import ihh.spellbound.item.Icicle;
import ihh.spellbound.item.IcyGrip;
import ihh.spellbound.item.InstantLevitation;
import ihh.spellbound.item.LightningBolt;
import ihh.spellbound.item.ObsidianWall;
import ihh.spellbound.item.PanicRoom;
import ihh.spellbound.item.Push;
import ihh.spellbound.item.StoneWall;
import ihh.spellbound.item.SummonSkeleton;
import ihh.spellbound.item.SummonWitherSkeleton;
import ihh.spellbound.item.SummonWolf;
import ihh.spellbound.item.Taser;
import ihh.spellbound.item.Torchlight;
import ihh.spellbound.item.WailOfTheSheWolf;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.potion.EffectInstance;
import net.minecraft.potion.Effects;
import net.minecraftforge.fml.RegistryObject;

public final class ItemInit implements IInit {
    public static final Item.Properties PROP = new Item.Properties().group(Spellbound.GROUP);
    public static final RegistryObject<Item> DECAYING_BEDROCK = ITEMS.register("decaying_bedrock", () -> new BlockItem(BlockInit.DECAYING_BEDROCK.get(), PROP));
    public static final RegistryObject<Item> DECAYING_OBSIDIAN = ITEMS.register("decaying_obsidian", () -> new BlockItem(BlockInit.DECAYING_OBSIDIAN.get(), PROP));
    public static final RegistryObject<Item> SPECKLED_RED_MAGIC_MUSHROOM = ITEMS.register("speckled_red_magic_mushroom", () -> new BlockItem(BlockInit.SPECKLED_RED_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> SPECKLED_ORANGE_MAGIC_MUSHROOM = ITEMS.register("speckled_orange_magic_mushroom", () -> new BlockItem(BlockInit.SPECKLED_ORANGE_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> SPECKLED_PINK_MAGIC_MUSHROOM = ITEMS.register("speckled_pink_magic_mushroom", () -> new BlockItem(BlockInit.SPECKLED_PINK_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> SPECKLED_BLUE_MAGIC_MUSHROOM = ITEMS.register("speckled_blue_magic_mushroom", () -> new BlockItem(BlockInit.SPECKLED_BLUE_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> LIGHT_BLUE_MAGIC_MUSHROOM = ITEMS.register("light_blue_magic_mushroom", () -> new BlockItem(BlockInit.LIGHT_BLUE_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> ORANGE_MAGIC_MUSHROOM = ITEMS.register("orange_magic_mushroom", () -> new BlockItem(BlockInit.ORANGE_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> YELLOW_MAGIC_MUSHROOM = ITEMS.register("yellow_magic_mushroom", () -> new BlockItem(BlockInit.YELLOW_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> PURPLE_MAGIC_MUSHROOM = ITEMS.register("purple_magic_mushroom", () -> new BlockItem(BlockInit.PURPLE_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> RAINBOW_MAGIC_MUSHROOM = ITEMS.register("rainbow_magic_mushroom", () -> new BlockItem(BlockInit.RAINBOW_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> GOLD_MAGIC_MUSHROOM = ITEMS.register("gold_magic_mushroom", () -> new BlockItem(BlockInit.GOLD_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> GRAY_MAGIC_MUSHROOM = ITEMS.register("gray_magic_mushroom", () -> new BlockItem(BlockInit.GRAY_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> BLACK_MAGIC_MUSHROOM = ITEMS.register("black_magic_mushroom", () -> new BlockItem(BlockInit.BLACK_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> WHITE_MAGIC_MUSHROOM = ITEMS.register("white_magic_mushroom", () -> new BlockItem(BlockInit.WHITE_MAGIC_MUSHROOM.get(), PROP));
    public static final RegistryObject<Item> BASE_TABLET = ITEMS.register("base_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> COLD_TABLET = ITEMS.register("cold_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> FIRE_TABLET = ITEMS.register("fire_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> LIGHTNING_TABLET = ITEMS.register("lightning_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> SUMMON_TABLET = ITEMS.register("summon_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> DISRUPTION_TABLET = ITEMS.register("disruption_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> DIVINATION_TABLET = ITEMS.register("divination_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> PROTECTION_TABLET = ITEMS.register("protection_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> MUNDANE_TABLET = ITEMS.register("mundane_tablet", () -> new Item(PROP));
    public static final RegistryObject<Item> ICY_GRIP = ITEMS.register("icy_grip", IcyGrip::new);
    public static final RegistryObject<Item> ICICLE = ITEMS.register("icicle", Icicle::new);
    public static final RegistryObject<Item> COLD_BLAST = ITEMS.register("cold_blast", ColdBlast::new);
    public static final RegistryObject<Item> COLD_SHIELD = ITEMS.register("cold_shield", () -> new BeneficialPotionSpell(Config.COLD_SHIELD_CHARGE_TIME, new EffectInstance(EffectInit.cold_shield, Config.COLD_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> FLAMING_HANDS = ITEMS.register("flaming_hands", FlamingHands::new);
    public static final RegistryObject<Item> FIREBALL = ITEMS.register("fireball", Fireball::new);
    public static final RegistryObject<Item> GREATER_FIREBALL = ITEMS.register("greater_fireball", GreaterFireball::new);
    public static final RegistryObject<Item> FIRE_SHIELD = ITEMS.register("fire_shield", () -> new BeneficialPotionSpell(Config.FIRE_SHIELD_CHARGE_TIME, new EffectInstance(EffectInit.fire_shield, Config.FIRE_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> TASER = ITEMS.register("taser", Taser::new);
    public static final RegistryObject<Item> LIGHTNING_BOLT = ITEMS.register("lightning_bolt", LightningBolt::new);
    public static final RegistryObject<Item> AREA_LIGHTNING = ITEMS.register("area_lightning", AreaLightning::new);
    public static final RegistryObject<Item> LIGHTNING_SHIELD = ITEMS.register("lightning_shield", () -> new BeneficialPotionSpell(Config.LIGHTNING_SHIELD_CHARGE_TIME, new EffectInstance(EffectInit.lightning_shield, Config.LIGHTNING_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> SUMMON_WOLF = ITEMS.register("summon_wolf", SummonWolf::new);
    public static final RegistryObject<Item> SUMMON_SKELETON = ITEMS.register("summon_skeleton", SummonSkeleton::new);
    public static final RegistryObject<Item> SUMMON_WITHER_SKELETON = ITEMS.register("summon_wither_skeleton", SummonWitherSkeleton::new);
    public static final RegistryObject<Item> SURGE_SHIELD = ITEMS.register("surge_shield", () -> new BeneficialPotionSpell(Config.SURGE_SHIELD_CHARGE_TIME, new EffectInstance(EffectInit.surge_shield, Config.SURGE_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> SPELL_SHIELD = ITEMS.register("spell_shield", () -> new BeneficialPotionSpell(Config.SPELL_SHIELD_CHARGE_TIME, new EffectInstance(EffectInit.spell_shield, Config.SPELL_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> ARCHMAGIC = ITEMS.register("archmagic", () -> new BeneficialPotionSpell(Config.ARCHMAGIC_CHARGE_TIME, new EffectInstance(EffectInit.archmagic, Config.ARCHMAGIC_DURATION.get())));
    public static final RegistryObject<Item> DISINTEGRATE = ITEMS.register("disintegrate", Disintegrate::new);
    public static final RegistryObject<Item> ELEMENTAL_FURY = ITEMS.register("elemental_fury", ElementalFury::new);
    public static final RegistryObject<Item> PANIC_ROOM = ITEMS.register("panic_room", PanicRoom::new);
    public static final RegistryObject<Item> WAIL_OF_THE_SHE_WOLF = ITEMS.register("wail_of_the_she_wolf", WailOfTheSheWolf::new);
    public static final RegistryObject<Item> BREACH = ITEMS.register("breach", Breach::new);
    public static final RegistryObject<Item> CHAOS = ITEMS.register("chaos", () -> new HarmfulPotionSpell(Config.CHAOS_CHARGE_TIME, new EffectInstance(EffectInit.chaos, Config.CHAOS_DURATION.get())));
    public static final RegistryObject<Item> MISCAST_MAGIC = ITEMS.register("miscast_magic", () -> new HarmfulPotionSpell(Config.MISCAST_MAGIC_CHARGE_TIME, new EffectInstance(EffectInit.miscast_magic, Config.MISCAST_MAGIC_DURATION.get())));
    public static final RegistryObject<Item> DIMENSION_DOOR = ITEMS.register("dimension_door", DimensionDoor::new);
    public static final RegistryObject<Item> COOKIE_CHEST = ITEMS.register("cookie_chest", CookieChest::new);
    public static final RegistryObject<Item> BEDROCK_WALL = ITEMS.register("bedrock_wall", BedrockWall::new);
    public static final RegistryObject<Item> OBSIDIAN_WALL = ITEMS.register("obsidian_wall", ObsidianWall::new);
    public static final RegistryObject<Item> STONE_WALL = ITEMS.register("stone_wall", StoneWall::new);
    public static final RegistryObject<Item> BLINK = ITEMS.register("blink", () -> new BeneficialPotionSpell(Config.BLINK_CHARGE_TIME, new EffectInstance(Effects.INVISIBILITY, Config.BLINK_DURATION.get())));
    public static final RegistryObject<Item> COLOR_SPRAY = ITEMS.register("color_spray", ColorSpray::new);
    public static final RegistryObject<Item> PUSH = ITEMS.register("push", Push::new);
    public static final RegistryObject<Item> ADVANCE_TIME = ITEMS.register("advance_time", AdvanceTime::new);
    public static final RegistryObject<Item> CHANGE_WEATHER = ITEMS.register("change_weather", ChangeWeather::new);
    public static final RegistryObject<Item> FISH_FORM = ITEMS.register("fish_form", () -> new BeneficialPotionSpell(Config.FISH_FORM_CHARGE_TIME, new EffectInstance(Effects.WATER_BREATHING, Config.FISH_FORM_DURATION.get())));
    public static final RegistryObject<Item> FLIGHT = ITEMS.register("flight", () -> new BeneficialPotionSpell(Config.FLIGHT_CHARGE_TIME, new EffectInstance(EffectInit.flight, Config.FLIGHT_DURATION.get())));
    public static final RegistryObject<Item> HASTE = ITEMS.register("haste", () -> new BeneficialPotionSpell(Config.HASTE_CHARGE_TIME, new EffectInstance(Effects.HASTE, Config.HASTE_DURATION.get())));
    public static final RegistryObject<Item> INSTANT_LEVITATION = ITEMS.register("instant_levitation", InstantLevitation::new);
    public static final RegistryObject<Item> TORCHLIGHT = ITEMS.register("torchlight", Torchlight::new);

    public static void init() {
    }
}
