package ihh.spellbound.init;

import ihh.spellbound.Config;
import ihh.spellbound.Spellbound;
import ihh.spellbound.item.AdvanceTime;
import ihh.spellbound.item.BedrockWall;
import ihh.spellbound.item.ChangeWeather;
import ihh.spellbound.item.CookieChest;
import ihh.spellbound.item.DimensionDoor;
import ihh.spellbound.item.InstantLevitation;
import ihh.spellbound.item.ObsidianWall;
import ihh.spellbound.item.PanicRoom;
import ihh.spellbound.item.PotionSpell;
import ihh.spellbound.item.ProjectileSpell;
import ihh.spellbound.item.StoneWall;
import ihh.spellbound.item.Torchlight;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.potion.EffectInstance;
import net.minecraft.potion.Effects;
import net.minecraftforge.fml.RegistryObject;

public final class ItemInit implements IInit {
    public static final Item.Properties GROUP = new Item.Properties().group(Spellbound.GROUP);
    public static final RegistryObject<Item> DECAYING_BEDROCK = ITEMS.register("decaying_bedrock", () -> new BlockItem(BlockInit.DECAYING_BEDROCK.get(), GROUP));
    public static final RegistryObject<Item> DECAYING_OBSIDIAN = ITEMS.register("decaying_obsidian", () -> new BlockItem(BlockInit.DECAYING_OBSIDIAN.get(), GROUP));
    public static final RegistryObject<Item> SPECKLED_RED_MAGIC_MUSHROOM = ITEMS.register("speckled_red_magic_mushroom", () -> new BlockItem(BlockInit.SPECKLED_RED_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> SPECKLED_ORANGE_MAGIC_MUSHROOM = ITEMS.register("speckled_orange_magic_mushroom", () -> new BlockItem(BlockInit.SPECKLED_ORANGE_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> SPECKLED_PINK_MAGIC_MUSHROOM = ITEMS.register("speckled_pink_magic_mushroom", () -> new BlockItem(BlockInit.SPECKLED_PINK_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> SPECKLED_BLUE_MAGIC_MUSHROOM = ITEMS.register("speckled_blue_magic_mushroom", () -> new BlockItem(BlockInit.SPECKLED_BLUE_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> LIGHT_BLUE_MAGIC_MUSHROOM = ITEMS.register("light_blue_magic_mushroom", () -> new BlockItem(BlockInit.LIGHT_BLUE_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> ORANGE_MAGIC_MUSHROOM = ITEMS.register("orange_magic_mushroom", () -> new BlockItem(BlockInit.ORANGE_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> YELLOW_MAGIC_MUSHROOM = ITEMS.register("yellow_magic_mushroom", () -> new BlockItem(BlockInit.YELLOW_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> PURPLE_MAGIC_MUSHROOM = ITEMS.register("purple_magic_mushroom", () -> new BlockItem(BlockInit.PURPLE_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> RAINBOW_MAGIC_MUSHROOM = ITEMS.register("rainbow_magic_mushroom", () -> new BlockItem(BlockInit.RAINBOW_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> GOLD_MAGIC_MUSHROOM = ITEMS.register("gold_magic_mushroom", () -> new BlockItem(BlockInit.GOLD_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> GRAY_MAGIC_MUSHROOM = ITEMS.register("gray_magic_mushroom", () -> new BlockItem(BlockInit.GRAY_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> BLACK_MAGIC_MUSHROOM = ITEMS.register("black_magic_mushroom", () -> new BlockItem(BlockInit.BLACK_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> WHITE_MAGIC_MUSHROOM = ITEMS.register("white_magic_mushroom", () -> new BlockItem(BlockInit.WHITE_MAGIC_MUSHROOM.get(), GROUP));
    public static final RegistryObject<Item> BASE_TABLET = ITEMS.register("base_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> COLD_TABLET = ITEMS.register("cold_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> FIRE_TABLET = ITEMS.register("fire_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> LIGHTNING_TABLET = ITEMS.register("lightning_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> SUMMON_TABLET = ITEMS.register("summon_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> DISRUPTION_TABLET = ITEMS.register("disruption_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> DIVINATION_TABLET = ITEMS.register("divination_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> PROTECTION_TABLET = ITEMS.register("protection_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> MUNDANE_TABLET = ITEMS.register("mundane_tablet", () -> new Item(GROUP));
    public static final RegistryObject<Item> ICY_GRIP = ITEMS.register("icy_grip", () -> new ProjectileSpell(Config.ICY_GRIP_USE_DURATION, EntityInit.ICY_GRIP));
    public static final RegistryObject<Item> ICICLE = ITEMS.register("icicle", () -> new ProjectileSpell(Config.ICICLE_USE_DURATION, EntityInit.ICICLE));
    public static final RegistryObject<Item> COLD_BLAST = ITEMS.register("cold_blast", () -> new ProjectileSpell(Config.COLD_BLAST_USE_DURATION, EntityInit.COLD_BLAST));
    public static final RegistryObject<Item> COLD_SHIELD = ITEMS.register("cold_shield", () -> new PotionSpell(Config.COLD_SHIELD_USE_DURATION, new EffectInstance(EffectInit.cold_shield, Config.COLD_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> FLAMING_HANDS = ITEMS.register("flaming_hands", () -> new ProjectileSpell(Config.FLAMING_HANDS_USE_DURATION, EntityInit.FLAMING_HANDS));
    public static final RegistryObject<Item> FIREBALL = ITEMS.register("fireball", () -> new ProjectileSpell(Config.FIREBALL_USE_DURATION, EntityInit.FIREBALL));
    public static final RegistryObject<Item> GREATER_FIREBALL = ITEMS.register("greater_fireball", () -> new ProjectileSpell(Config.GREATER_FIREBALL_USE_DURATION, EntityInit.GREATER_FIREBALL));
    public static final RegistryObject<Item> FIRE_SHIELD = ITEMS.register("fire_shield", () -> new PotionSpell(Config.FIRE_SHIELD_USE_DURATION, new EffectInstance(EffectInit.fire_shield, Config.FIRE_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> TASER = ITEMS.register("taser", () -> new ProjectileSpell(Config.TASER_USE_DURATION, EntityInit.TASER));
    public static final RegistryObject<Item> LIGHTNING_BOLT = ITEMS.register("lightning_bolt", () -> new ProjectileSpell(Config.LIGHTNING_BOLT_USE_DURATION, EntityInit.LIGHTNING_BOLT));
    public static final RegistryObject<Item> AREA_LIGHTNING = ITEMS.register("area_lightning", () -> new ProjectileSpell(Config.AREA_LIGHTNING_USE_DURATION, EntityInit.AREA_LIGHTNING));
    public static final RegistryObject<Item> LIGHTNING_SHIELD = ITEMS.register("lightning_shield", () -> new PotionSpell(Config.LIGHTNING_SHIELD_USE_DURATION, new EffectInstance(EffectInit.lightning_shield, Config.LIGHTNING_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> SUMMON_WOLF = ITEMS.register("summon_wolf", () -> new ProjectileSpell(Config.SUMMON_WOLF_USE_DURATION, EntityInit.SUMMON_WOLF));
    public static final RegistryObject<Item> SUMMON_SKELETON = ITEMS.register("summon_skeleton", () -> new ProjectileSpell(Config.SUMMON_SKELETON_USE_DURATION, EntityInit.SUMMON_SKELETON));
    public static final RegistryObject<Item> SUMMON_WITHER_SKELETON = ITEMS.register("summon_wither_skeleton", () -> new ProjectileSpell(Config.SUMMON_WITHER_SKELETON_USE_DURATION, EntityInit.SUMMON_WITHER_SKELETON));
    public static final RegistryObject<Item> SURGE_SHIELD = ITEMS.register("surge_shield", () -> new PotionSpell(Config.SURGE_SHIELD_USE_DURATION, new EffectInstance(EffectInit.surge_shield, Config.SURGE_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> SPELL_SHIELD = ITEMS.register("spell_shield", () -> new PotionSpell(Config.SPELL_SHIELD_USE_DURATION, new EffectInstance(EffectInit.spell_shield, Config.SPELL_SHIELD_DURATION.get())));
    public static final RegistryObject<Item> ARCHMAGIC = ITEMS.register("archmagic", () -> new PotionSpell(Config.ARCHMAGIC_USE_DURATION, new EffectInstance(EffectInit.archmagic, Config.ARCHMAGIC_DURATION.get())));
    public static final RegistryObject<Item> DISINTEGRATE = ITEMS.register("disintegrate", () -> new ProjectileSpell(Config.DISINTEGRATE_USE_DURATION, EntityInit.DISINTEGRATE));
    public static final RegistryObject<Item> ELEMENTAL_FURY = ITEMS.register("elemental_fury", () -> new ProjectileSpell(Config.ELEMENTAL_FURY_USE_DURATION, EntityInit.ELEMENTAL_FURY));
    public static final RegistryObject<Item> PANIC_ROOM = ITEMS.register("panic_room", PanicRoom::new);
    public static final RegistryObject<Item> WAIL_OF_THE_SHE_WOLF = ITEMS.register("wail_of_the_she_wolf", () -> new ProjectileSpell(Config.WAIL_OF_THE_SHE_WOLF_USE_DURATION, EntityInit.WAIL_OF_THE_SHE_WOLF));
    public static final RegistryObject<Item> BREACH = ITEMS.register("breach", () -> new ProjectileSpell(Config.BREACH_USE_DURATION, EntityInit.BREACH));
    public static final RegistryObject<Item> CHAOS = ITEMS.register("chaos", () -> new ProjectileSpell(Config.CHAOS_USE_DURATION, EntityInit.CHAOS));
    public static final RegistryObject<Item> MISCAST_MAGIC = ITEMS.register("miscast_magic", () -> new ProjectileSpell(Config.MISCAST_MAGIC_USE_DURATION, EntityInit.MISCAST_MAGIC));
    public static final RegistryObject<Item> DIMENSION_DOOR = ITEMS.register("dimension_door", DimensionDoor::new);
    public static final RegistryObject<Item> COOKIE_CHEST = ITEMS.register("cookie_chest", CookieChest::new);
    public static final RegistryObject<Item> BEDROCK_WALL = ITEMS.register("bedrock_wall", BedrockWall::new);
    public static final RegistryObject<Item> OBSIDIAN_WALL = ITEMS.register("obsidian_wall", ObsidianWall::new);
    public static final RegistryObject<Item> STONE_WALL = ITEMS.register("stone_wall", StoneWall::new);
    public static final RegistryObject<Item> BLINK = ITEMS.register("blink", () -> new PotionSpell(Config.BLINK_USE_DURATION, new EffectInstance(Effects.INVISIBILITY, Config.BLINK_DURATION.get())));
    public static final RegistryObject<Item> COLOR_SPRAY = ITEMS.register("color_spray", () -> new ProjectileSpell(Config.COLOR_SPRAY_USE_DURATION, EntityInit.COLOR_SPRAY));
    public static final RegistryObject<Item> PUSH = ITEMS.register("push", () -> new ProjectileSpell(Config.PUSH_USE_DURATION, EntityInit.PUSH));
    public static final RegistryObject<Item> ADVANCE_TIME = ITEMS.register("advance_time", AdvanceTime::new);
    public static final RegistryObject<Item> CHANGE_WEATHER = ITEMS.register("change_weather", ChangeWeather::new);
    public static final RegistryObject<Item> FISH_FORM = ITEMS.register("fish_form", () -> new PotionSpell(Config.FISH_FORM_USE_DURATION, new EffectInstance(Effects.WATER_BREATHING, Config.FISH_FORM_DURATION.get())));
    public static final RegistryObject<Item> FLIGHT = ITEMS.register("flight", () -> new PotionSpell(Config.FLIGHT_USE_DURATION, new EffectInstance(EffectInit.flight, Config.FLIGHT_DURATION.get())));
    public static final RegistryObject<Item> HASTE = ITEMS.register("haste", () -> new PotionSpell(Config.HASTE_USE_DURATION, new EffectInstance(Effects.HASTE, Config.HASTE_DURATION.get())));
    public static final RegistryObject<Item> INSTANT_LEVITATION = ITEMS.register("instant_levitation", InstantLevitation::new);
    public static final RegistryObject<Item> TORCHLIGHT = ITEMS.register("torchlight", Torchlight::new);

    public static void init() {
    }
}
